### ISSUE TITLE
Browser is never released until Servoy is closed

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/jxbrowser_bean#1]
I have a customer testing this and they embed NGClient in smart client to use a cool component
They quickly exhaust all of their licenses because the session is not released until the IDE closes.
It seems to create a new NGClient session evertime the bean is shown

There is a method dispose() on the Browser class.
https://www.teamdev.com/downloads/jxbrowser/javadoc/com/teamdev/jxbrowser/chromium/Browser.html#dispose--

We should at least call that when the bean unloads

**Comment by lvostinar** [comment]
Fixed this and released a new version (1.0.1)
